# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirements.txt .
# Install dependencies with an increased timeout
RUN pip install --no-cache-dir -r requirements.txt --timeout=600


# Copy the FastAPI app into the container
COPY server.py /app

# Expose the FastAPI port
EXPOSE 8080

# Set the command to run the FastAPI app
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8080"]
